// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoO7I_6XFZgal_MoYMJRgPLeTBkpSg7rA',
    appId: '1:263615483057:web:1c9aa8b0bb4a61501f2690',
    messagingSenderId: '263615483057',
    projectId: 'basic-6b33a',
    authDomain: 'basic-6b33a.firebaseapp.com',
    storageBucket: 'basic-6b33a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrLr1VDs3RhMADACVTlgRTJFXiOYaPyVM',
    appId: '1:263615483057:android:a4110d22b8b8bfd71f2690',
    messagingSenderId: '263615483057',
    projectId: 'basic-6b33a',
    storageBucket: 'basic-6b33a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCpRsvH3I6TACzWmjtP4BXWpOgfQDC1VA',
    appId: '1:263615483057:ios:bb662d81c0e167dd1f2690',
    messagingSenderId: '263615483057',
    projectId: 'basic-6b33a',
    storageBucket: 'basic-6b33a.firebasestorage.app',
    iosBundleId: 'com.example.hostelManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCpRsvH3I6TACzWmjtP4BXWpOgfQDC1VA',
    appId: '1:263615483057:ios:bb662d81c0e167dd1f2690',
    messagingSenderId: '263615483057',
    projectId: 'basic-6b33a',
    storageBucket: 'basic-6b33a.firebasestorage.app',
    iosBundleId: 'com.example.hostelManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoO7I_6XFZgal_MoYMJRgPLeTBkpSg7rA',
    appId: '1:263615483057:web:1c9aa8b0bb4a61501f2690',
    messagingSenderId: '263615483057',
    projectId: 'basic-6b33a',
    authDomain: 'basic-6b33a.firebaseapp.com',
    storageBucket: 'basic-6b33a.firebasestorage.app',
  );

}